services:
  identity:
    image: ${IDENTITY_IMAGE:-cortesa/link-wars-identity:latest}
    networks:
      - link-wars-net
    restart: unless-stopped

  cashier:
    image: ${CASHIER_IMAGE:-cortesa/link-wars-cashier:latest}
    depends_on:
      - identity
    networks:
      - link-wars-net
    restart: unless-stopped

  game-server:
    image: ${GAME_SERVER_IMAGE:-cortesa/link-wars-game-server:latest}
    depends_on:
      - identity
    networks:
      - link-wars-net
    restart: unless-stopped

  client-web:
    image: ${CLIENT_WEB_IMAGE:-cortesa/link-wars-client-web:latest}
    depends_on:
      - game-server
    networks:
      - link-wars-net
    restart: unless-stopped

networks:
  link-wars-net:
    driver: bridge

volumes:
  db-data:
  redis-data:
