services:
  identity:
    image: cortesa/link-wars-identity:${STG_TAG:-staging}
    environment:
      - NODE_ENV=staging
    ports:
      - "8080:8080"

  cashier:
    image: cortesa/link-wars-cashier:${STG_TAG:-staging}
    environment:
      - NODE_ENV=staging
    ports:
      - "3001:3001"

  game-server:
    image: cortesa/link-wars-game-server:${STG_TAG:-staging}
    environment:
      - NODE_ENV=staging
    ports:
      - "2567:2567"

  client-web:
    image: cortesa/link-wars-client-web:${STG_TAG:-staging}
    environment:
      - NODE_ENV=staging
    ports:
      - "80:80"
